"""Create tables for items and categories

Revision ID: 0011facb200d
Revises: 
Create Date: 2024-12-25 15:22:26.821928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0011facb200d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_categories',
    sa.Column('item_category_name', sa.String(), nullable=False),
    sa.Column('item_category_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('item_category_id')
    )
    op.create_index(op.f('ix_item_categories_item_category_id'), 'item_categories', ['item_category_id'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('card_url', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('item_category_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_category_id'], ['item_categories.item_category_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=False)
    op.create_table('items',
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('item_category_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_category_id'], ['item_categories.item_category_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_items_item_id'), 'items', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_item_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_item_categories_item_category_id'), table_name='item_categories')
    op.drop_table('item_categories')
    # ### end Alembic commands ###
